### ISSUE TITLE
Button Group (linked buttons)

### ISSUE THREAD

**Issue by jonvitale** [stefanwalther/sense-navigation#100]
Feature Request:

Stefan, one of the issues we are having on mobile is that if we have multiple buttons that are related, they may not show up sequentially. It seems that mobile displays objects from left to right. So, if a group of buttons are aligned vertically, they may be displayed out of order.

Do you think there is a way to enhance this extension so that multiple buttons could be part of the same object?

Thank you,

Jonathan

**Comment by stefanwalther** [comment]
I was thinking of that actually for a while, but cannot find a good way how the current property panel in Qlik Sense would support that, because then I'd need

- n-Buttons, each of them with n-actions, so it's some kind of a nested scenario which is not supported out of the box by the property panel
- Sure I could inject some custom dialog into the property panel, but I was trying to stick as much as possible to the officially supported APIs ...

Makes sense?
I'll close this; please feel free to re-open if you have a great idea or even a PR to get this functionality in and sticking to the official APIs at the same time.
