### ISSUE TITLE
Select not only Values for Fields but extend to expression (as Value) for expresion (as Field)

### ISSUE THREAD

**Issue by anghelf** [stefanwalther/sense-navigation#106]
### Description

Hi Stefan,

I would like to use your extension in order to aply advances filters, so I would like to use similar functionality as 'Select Value in Field' but to be able to include an expression as Field and another expression as Value. 

### Steps to Reproduce

1. select as Action 'Select Value in Field'
2. input if(Field1=valueofField1,1,0) as Field expression 
3. if(Field2=valueofField2,1,0) as Value expression

##### Expected behavior

The expected behavior would be when you click on the button, the filter Field1=valueofField1 and Field2=valueofField2 to be applied

##### Actual behavior

nothing - no filter is applied

##### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[x] Desktop
[ ] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Thx for reporting, I need to investigate.
Could you please provide which version you have used, thx. See above:

![image](https://user-images.githubusercontent.com/669728/34726100-53a00c32-f553-11e7-8781-fa88ee31d533.png)

**Comment by stefanwalther** [comment]
Hi, just to be clear. Is it this what you are trying to achieve:

![image](https://user-images.githubusercontent.com/669728/35319134-814707b2-00ac-11e8-9181-028c829358a1.png)

So if the value in `Dim1` would be `A`, then

- `a` would be selected in field `Dim2`, otherwise
- `x` would be selected in field `Dim3`

I have only tested in the (soon to be released #58), but can confirm that this doesn't work as expected. But interesting use case though. I have an idea why it does not work but have to dig deeper into it ...

**Comment by stefanwalther** [comment]
If my description above is correct, I have found the issue and solved it with #124.

**Comment by stefanwalther** [comment]
Ping ^ @anghelf

**Comment by stefanwalther** [comment]
Closing as I haven't received any answer. Please feel free, @anghelf, to re-open this issue as needed.
