### ISSUE TITLE
Extension (v1.0 beta) does not work in internet explorer

### ISSUE THREAD

**Issue by JMHellendoorn** [stefanwalther/sense-navigation#140]
### Description

1.0.0-beta-08 of this extension doesn't work in Internet Explorer 11

### Steps to Reproduce

1. Create a button in Chrome, doesn't have to have any properties
2. Open the same tab in Internet Explorer 11, it doesn't show anything.

##### Expected behavior

Button visible and usable in IE.

##### Actual behavior

Button not visible in IE.

### Environment
Internet Explorer 11, Qlik Sense server November 2017 patch 2

##### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[x] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[x] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.0.0-beta-08
* Browser: Internet Explorer 11
* Qlik Sense: November 2017 Patch 2
* Operating system: Windows 10
* [Other relevant versions]

**Comment by JMHellendoorn** [comment]
![sense-navigation internet explorer 1](https://user-images.githubusercontent.com/33353204/39984116-62cfd69c-575a-11e8-89fd-f556d5584d5d.png)
Please find attached a screenshot of the issue.

**Comment by stefanwalther** [comment]
Yes, seems that I need to do some testing on IE ... ;-(

**Comment by stefanwalther** [comment]
Hi @JMHellendoorn, please try the new RC-03: 

- Direct Download: https://github.com/stefanwalther/sense-navigation/raw/v1.0/build/sense-navigation_v1.0.0-rc-03.zip
- Branch: https://github.com/stefanwalther/sense-navigation/tree/v1.0

I found the error (fixed with #159):
- In Qlik Sense Desktop and older browsers (like IE 11) JavaScripts `const` and `let` did not work, which actually broken the extension.
- Fixed that now and tested in
  - Qlik Sense Desktop June 2018 (inside the Desktop, not only using http://localhost:4848)
  - Firefox
  - Chrome
  - Edge

Please give it a try an let me know.
Thx a lot in advance!

**Comment by JMHellendoorn** [comment]
Thanks @stefanwalther 
The solution works.

**Comment by stefanwalther** [comment]
Thx a lot for verifying. Then I can lose this issue ... ;-)
