### ISSUE TITLE
Mobile view enhancement//Multiple buttons in same object?

### ISSUE THREAD

**Issue by MikaelSc** [stefanwalther/sense-navigation#21]
Fantastic extension!!
Would it be possible to add multiple buttons in the same object, as the rendering on small screens for small and wide single objects in qliksense is not optimal: 

![image](https://cloud.githubusercontent.com/assets/15074460/10416638/2e1f1a8c-701e-11e5-84fa-a3c99e61a684.png)

**Comment by stefanwalther** [comment]
Hi,

adding additional buttons into one object is unfortunately not really possible, because there is currently not good - official - way to bring this into the property panel. As soon as there is better support for that in the official API this can be solved.
But I'll have a look in the mobile output, maybe there's something I can improve there.

**Comment by tmaure06** [comment]
Hello Stephan

We are fan of your extensions which are always nice polished before being released. This new example is as always working very nicely with many interesting capabilities.
Anyway, I also would love to have the capability to add several buttons to use this as an application navigation menu, this would be a killer enhancement!
Indeed adding buttons one by one is not very comfortable as we cannot create a single master item with all buttons and it creates empty space between buttons...

Thomas

**Comment by stefanwalther** [comment]
As mentioned above, I fully understand and would like to do that, but the current public API how to define the property panel doesn't really allow that and I definitely only want to build stuff based on the Public API ...

**Comment by stefanwalther** [comment]
Closing as there is still no public API I can use.
