### ISSUE TITLE
Document Chaining 2.0

### ISSUE THREAD

**Issue by jwarbington** [stefanwalther/sense-navigation#33]
Absolutely vital - the ability to jump to another app and carry over the current selections.

**Comment by stefanwalther** [comment]
Hi @jwarbington, absolutely.
In 2.2 there will be a new client API we can use for that, so called "App Integration API".
As soon as 2.2 is available I will upload a new version of this extension containing that kind of functionality.

**Comment by Jatin-Kakani** [comment]
Hi Stefan,

I am using this extension for jumping to another app while carrying the current selections.
I am passing the link to single configurator and passing the sheet id and selection values. 
However, in this case, I am not able to traverse between multiple sheets of the second dashboard. 
I am just able to go to the sheet whose id I passed along with the filter selections.
Could you please help me achieve this ?

Thanks.
Regards,
Jatin

**Comment by stefanwalther** [comment]
Unfortunately I didn't have enough time so far, but I am planning to add some quite generic functionality to sense-navigation which would enable what you are describing. Just needs a bit more testing before I publish it ...

**Comment by Jatin-Kakani** [comment]
Thank you for the reply Stefan !
Looking forward to see the feature soon :)

**Comment by danielm2** [comment]
Hey there, I'm also looking forward to this great feature - What do you think how much time do you need for implementation?

I checked the "App Integration API" on Qlik but for me it's not clear how you want to use that feature? Because it is only for including "dashboards" via iFrame..? Or would it be nothing else like a link: https://help.qlik.com/en-US/sense-developer/3.0/Subsystems/Mashups/Content/AppIntegrationAPI/app-integration-api-examples.htm and after clicking a new tab is opening the URL??

**Comment by stefanwalther** [comment]
Still working on some other features I'd like to submit first (n-actions). But I think it's not that far away, give me another 2-3 weeks ...

**Comment by stefanwalther** [comment]
@jwarbington see https://community.qlik.com/docs/DOC-14610

**Comment by stefanwalther** [comment]
I will not continue with this idea as difference between environments are significant (Desktop, Qlik Sense Enterprise, Qlik Cloud Services, Qlik Sense Cloud Business) and I want to keep this visualization extension as generic as possible.

Thx for your understanding!
