### ISSUE TITLE
sense-navigation not work in single configurator

### ISSUE THREAD

**Issue by dickychang** [stefanwalther/sense-navigation#38]
Hi,

I found that this sense-navigation button not working in single configurator. Is it not support for single configurator or i have miss out some important configuration?

**Comment by stefanwalther** [comment]
Thx for reporting, which version of sense-navigation and Single configurator are you using?

**Comment by stefanwalther** [comment]
@dickychang, please tell me which version you are using, thx.

**Comment by stefanwalther** [comment]
Adding to that: What would be the use case of using sense-navigation in the Single Configurator? Just realized that this doesn't really make sense, since sense-navigation is really meant to work within the Qlik Sense client and all/most of the actions will definitely only work within Qlik Sense client.

Closing therefore this issue.
