### ISSUE TITLE
Button action not working in mobile

### ISSUE THREAD

**Issue by arulsettu** [stefanwalther/sense-navigation#56]
HI,
    First thanks for the extension. really a nice one. I ma facing a issue while using the app in mobile the button action not working. its works well in PC. can you please give a quick solution.

Thanks

**Comment by stefanwalther** [comment]
On mobile you typically have to click twice, first to enter the full-screen mode and then you can click the button. This is the default behavior of all visualizations in Qlik Sense. 
Did you try that? Can you please double-check if this is the case. If so there is not much I can do. If there is something else, I'll investigate.

Why version of sense-navigation are you using?

**Comment by arulsettu** [comment]
Thanks for quick reply. clicking twice is default behavior is ok. i set the action to next page in that case not working. other actions like navigating to particular sheets are fine..


Thank you very much...

**Comment by stefanwalther** [comment]
OK, I'll have a look into it ...

**Comment by arulsettu** [comment]
Thank you

**Comment by stefanwalther** [comment]
Thx @arulsettu, I could reproduce what you have described. Unfortunately, this is nothing I can fix in sense-navigation, it is a bug in the Navigation API I was using. I filed this as a bug in Qlik Sense, and hope that we can fix it soon.
As this is a third-party-bug (from a sense-navigation perspective), I'll close this issue. As soon as this is fixed in Qlik Sense and its APIs, this will also work again.
