### ISSUE TITLE
sense sheet navigation is not working 

### ISSUE THREAD

**Issue by samybics** [stefanwalther/sense-navigation#64]
sheet navigation is not working in single configurator with or without iframe on qlik sense 2.4 server as well as qlik sense 3.0 desktop. 
Please provide me any sample which works on single configurator

**Comment by stefanwalther** [comment]
Haven't really tested it in the single configurator, since the main use-case is to use it within Qlik Sense ...
What exactly is not working?
Which version of sense-navigation (have a look into the .qext file) are you using?

**Comment by samybics** [comment]
Hi Stefan,

             Sense navigation is not working. When I have four navigation
button with four sheets mapped, The navigation button is not working on the
iframe url, where as it works on sense app in hub.

*.qext version is :0.8.1 *with qliksense 3.0



---
Thank you

With regards

Arockiasamy
Ph : +91 7639018872

**Comment by stefanwalther** [comment]
HI @samybics , 

sense-navigation was really developed to help with actions & navigations withing Qlik Sense. The next generation of sense-navigation ( #58 ) even extends that.
So any scenario you are describing (e.g. jumping to another sheet in a Mashup scenario or in an Iframe just cannot work).

This is not your fault, I should think of how actually an extension like this one should be disabled to be used in single-configurator or in mashups.

So I won't fix, hope you understand, but think about a long term solution, so that this misunderstanding cannot happen again.

Regards
Stefan
