### ISSUE TITLE
Apply Bookmark - looses action

### ISSUE THREAD

**Issue by retrocolor** [stefanwalther/sense-navigation#82]
Hi Stefan,

Thanks for your work on this extension! It is really helpful for my current project where I rely on Bookmarks.
I have one small question - I use the apply bookmark action with a button. 
If I set a button with specific bookmark and after that I recreate the bookmark with the same name and delete the old one - the button looses the functionality to apply 
the bookmark and I should recreate the action.
Is this a bug and why I loose the action of this button? Can I set the bookmark by its name? 

I use the extension with  QS 3.1 SR4 Server

Thanks,
Radi

**Comment by Colm-Kelly** [comment]
Hi Retrocolor,

I'm not a maintainer but I looked into the code - when setting a bookmark, the extension doesn't use the bookmark name, instead it uses the internal bookmark id. When you delete a bookmark and create a new one, that bookmark is assigned a new bookmark id, so from the extensions' point of view it's a totally different bookmark.

I think this is expected behavior.

**Comment by retrocolor** [comment]
Hi Colm-Kelly,

Thanks for the detailed explanation!

Radi

**Comment by stefanwalther** [comment]
Yes, can confirm that and therefore closing this issue.
