### ISSUE TITLE
Button appears in export to .pdf

### ISSUE THREAD

**Issue by forooghianj** [stefanwalther/sense-navigation#83]
Hi Stefan,

Love the extension - I'm using it above some of my visualisations instead of a title. Is it possible to allow export to .pdf so that the dashboard looks the same when exported?

Many Thanks,
Joe

**Comment by stefanwalther** [comment]
Hmm, in version v1.0 (https://github.com/stefanwalther/sense-navigation/tree/v1.0) I was thinking of that, but on purpose I have disabled the extension to be included in the export/pdf because I was thinking that in the PDF the button anyhow doesn't really have a meaning.

Curious to hear why you think it should be included?!

Regards
Stefan

**Comment by forooghianj** [comment]
Hi Stefan,

Completely understand your logic - I'm however using the buttons as titles above charts on a dashboard, which link to a different sheet corresponding to a more detailed view of that visualisation. Therefore the buttons form part of the styling/layout of the dashboard. Potentially not best practice from a performance point of view, but it seems to be the most logical way of fulfilling the requirement.

Kind Regards,
Joe

**Comment by stefanwalther** [comment]
Hmmmmm, got ... let me think of it ... I guess I can just enable it for export, shouldn't have any negative side-effects.

**Comment by forooghianj** [comment]
Wonderful - Thanks for the effort stefan.

**Comment by jonvitale** [comment]
Hi Stefan,

Is there any progress on this? I'm thinking about creating a fork just to include exporting. Do you know if it will work.

By the way, one of things we are doing is actually updating the text of the button when it has been selected. So, when a button sets a variable, on the label we use an expression to check that variable. If it is set we basically bold the button. So, in our case, exporting the button is necessary in pdfs because it will show which button has been selected.

Thank you,

Jonathan

**Comment by ManuelMAW** [comment]
Hi Stefan,
some news about this problem? I also need to export the button both in PDF and PPT.

Thank you!

**Comment by jonvitale** [comment]
@ManuelMAW,

You can try fixing this yourself. When you download the code, look for the file swr-sense-navigation.js. In that JavaScript file you'll see this snippet:

`support: {
        export: false,
        exportData: false,
        snapshot: false
      },`

Depending on which version of what you download, it may be minimized, so you'll have to search for these terms. Change "export:false" to "export:true", zip it back up, and upload it to the extensions folder. It seemed to work for me, but I can't guarantee there won't be unexpected issues. Let me know if you do come across any problems. 

Good luck

**Comment by stefanwalther** [comment]
@forooghianj, @ManuelMAW:
Solved for v1.0 (see #58), therefore closing.
v1.0 will be release super-soon.
