### ISSUE TITLE
Buttons are not displaying ture responsive behavior

### ISSUE THREAD

**Issue by rvijayanth** [stefanwalther/sense-navigation#85]
### Description
Sheet Navigational buttons are not displaying true responsive behavior when viewing extensions in mobile devices. Works perfectly when viewed application in laptops. 

We are using version": "0.5.14"

### Steps to Reproduce

1. Added buttons with QLIKSENSE's KPIs, tables and charts. 

Issue: 
All objects/extensions/widgets should integrate well each other to exhibit a true responsive behavior. This means no blank spaces between objects when used with QlikSense out of the box objects. 

Expectation:
We expect objects to stack on each other without any blank space. When viewed in landscape or portrait mode, sheet navigational buttons are put inside a fixed height div which is displaying a lot of blank space before showing the next button to any other qliksense objects.  

##### Actual behavior
There are blank spaces between objects/buttons
![capture](https://user-images.githubusercontent.com/4885651/27102510-884152d4-5053-11e7-8780-5beee17edcd5.JPG)

[What actually happened]

##### Operating system

```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[ ] Desktop
[ ] Enterprise
```

##### Browser

```
[ ] Chrome
[ ] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by stefanwalther** [comment]
Same as #21

**Comment by stefanwalther** [comment]
Thx for reporting. Unfortunately there is not a lot I can do here. This is the default behavior of Qlik Sense (see also a related issue #21).
There is a method called `getPreferredSize` in the client code which is used by Qlik's native object which actually addresses this problem and provides a way to solve this particular problem.

I have even added the corresponding code a while ago:

![image](https://user-images.githubusercontent.com/669728/27198935-7aa9cf94-5214-11e7-9793-c7adc0e52fc6.png)

[direct link to the code](https://github.com/stefanwalther/sense-navigation/blob/master/src/swr-sense-navigation.js#L45))

But I have decided not to add the solution to this extension since the method `getPreferredSize` is not exposed as a public API and I am trying to use as much as possible only public APIs to make "my" extension work in as many Qlik Sense versions as possible.

But that's the beauty of Open Source. Feel free to fork this project, enable this code and I hope you get where you want to be.

Regards
Stefan

P.S.: Closing this issue, as I will not fix it as long as there isn't a public, supported API I can use to solve this issue.
